name:                Poker
version:             0.1.0.0
github:              "francetem/Poker"
license:             BSD3
author:              "Francis Perez"
maintainer:          "francetem@hotmail.com"
copyright:           "2018 Francis Perez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Poker#readme>

dependencies:
- base >= 4.7 && < 5
- hold-em
- random

library:
  source-dirs: src

executables:
  Poker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Poker

tests:
  Poker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Poker
